{{- if .Values.job.enabled }}
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: ray-pipeline-job
  namespace: ray
spec:
  clusterSelector:
    ray.io/cluster: ray-cluster

  entrypoint: python /app/ray_pipeline.py --mode pipeline --env {{ .Values.job.env }}
  # race condition -- the submitter pod exits, it starts a 30-second countdown waiting for the Ray head to confirm SUCCEEDED
  shutdownAfterJobFinishes: true

  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  jobDeploymentStatusTransitionGracePeriodSeconds: {{ .Values.job.gracePeriodSeconds | default 300 }}

  runtimeEnvYAML: |
    env_vars:
      ICEBERG_WAREHOUSE: {{ include "ray-cluster.icebergWarehouse" . }}
      NESSIE_URI: {{ .Values.nessie.uri }}
      RAY_ADDRESS: http://ray-cluster-head-svc:8265
      GOOGLE_CLOUD_PROJECT: {{ .Values.global.projectId }}
      VERTEX_REGION: {{ .Values.global.vertexRegion }}
      SOURCE_A_PATH: {{ .Values.job.sourceAPath }}
      SOURCE_B_PATH: {{ .Values.job.sourceBPath }}

  submitterPodTemplate:
    metadata:
      labels:
        ray.io/component: job-submitter
    spec:
      serviceAccountName: ray-ksa
      restartPolicy: Never
      containers:
        - name: ray-job-submitter
          image: {{ include "ray-cluster.image" . }}
          imagePullPolicy: Always
          env:
            - name: RAY_ADDRESS
              value: http://ray-cluster-head-svc:8265
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
{{- end }}
{{- if .Values.trainJob.enabled }}
---
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: ray-train-job
  namespace: ray
spec:
  clusterSelector:
    ray.io/cluster: ray-cluster

  entrypoint: python /app/ray_pipeline.py --mode train
  shutdownAfterJobFinishes: true

  activeDeadlineSeconds: {{ .Values.trainJob.activeDeadlineSeconds }}
  ttlSecondsAfterFinished: {{ .Values.trainJob.ttlSecondsAfterFinished }}

  runtimeEnvYAML: |
    env_vars:
      ICEBERG_WAREHOUSE: {{ include "ray-cluster.icebergWarehouse" . }}
      NESSIE_URI: {{ .Values.nessie.uri }}
      MODEL_OUTPUT_PATH: {{ .Values.trainJob.modelOutputPath }}
      NUM_WORKERS: {{ .Values.trainJob.numWorkers | quote }}
      RAY_ADDRESS: http://ray-cluster-head-svc:8265
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python

  submitterPodTemplate:
    metadata:
      labels:
        ray.io/component: job-submitter
    spec:
      serviceAccountName: ray-ksa
      restartPolicy: Never
      containers:
        - name: ray-train-job-submitter
          image: {{ include "ray-cluster.image" . }}
          imagePullPolicy: Always
          env:
            - name: RAY_ADDRESS
              value: http://ray-cluster-head-svc:8265
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
{{- end }}
